### PR TITLE
[FIX] : Fix absolute import error

### PR DESCRIPTION
**Pull request by meetzaveri**

### CODE REVIEW

**Comment by reeversedev** [comment]
@meetzaveri your netlify build is failing. Are you sure that you have made changes in the latest code?

**Comment by meetzaveri** [comment]
Yeah I've got your latest code and commit was build upon that. Also checked netlify build errors, they are irrelevant to changes I've made.

**Comment by reeversedev** [comment]
I am merging the changes but we need to take a look at these errors later.

**Comment by meetzaveri** [comment]
Yes, we need to identify and debug accordingly

**Pull request merged**
